### ISSUE TITLE
Source code please

### ISSUE THREAD

**Issue by NYAN-x-CAT-is-My-Brother** [ScRiPt1337/Scripted-Ransomware-builder#1]
Please share the sourcecode of this ransomeware
Thanks

**Comment by kielec** [comment]
It keeps telling me to download the python 2.7 when I already have it installed

**Comment by Godseyex** [comment]
I created ransomware but how can I share the link to people's devices ????

**Comment by Godseyex** [comment]
yes same thing but I already installed it

**Comment by ScRiPt1337** [comment]
its very old dont use it anymore
